#
# Local configuration values (overrides _config.yml)
#
# To use these values, run:
#   `bundle exec jekyll serve --config _config_dev.yml,_config.yml -w`.
#

# Dev environment flag.
is_local: true

# GitHub defaults.
safe: true
lsi: false # better indexing for related posts
# Also see https://help.github.com/articles/repository-metadata-on-github-pages/

# Process posts with future dates on the local site.
future: true

# Sass compilation. Currently unused.
# sass:
#   style: :expanded
