#
# Local configuration values (overrides _config.yml)
#

# Dev environment flag.
is_local: true

# GitHub defaults.
highlighter: pygments
safe: true
lsi: false
# Also see https://help.github.com/articles/repository-metadata-on-github-pages/

# Sass compilation. Currently unused.
# sass:
#   style: :expanded
