#
# Local configuration values (overrides _config.yml)
#

# Dev environment flag
is_local: true

# GitHub defaults
highlighter: pygments
# github: see https://help.github.com/articles/repository-metadata-on-github-pages/
safe: true
lsi: false

# Sass compilation
sass:
  style: :expanded
