# Version (for cache busting)
version: 0.0.1

# Development or production?
is_local: false

# Site url (for use in pages)
url: http://www.cjbarnes.co.uk

# Permalinks
permalink: /blog/:title-:year-:month-:day/
relative_permalinks: false

# Pagination
paginate: 2
paginate_path: /blog/page:num

# Process _pages folder
include: ['_pages']

# Don't process working copies of images
exclude: ['.psd','.ai','.eps']

# Don't process posts with future dates
future: false

# Markdown parser
markdown: kramdown
kramdown:
  input: GFM # support GitHub-Flavored Markdown

# Enabled plugins
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
