#
# Configuration values (shared by production and development environments)
#

# Version (for cache busting).
version: 0.1.0

# Development or production?.
is_local: false

# Atom feed and SEO metadata.
title: web design by cJ barnes
description: Education and small business web developer based in Yorkshire and East Anglia, UK.
url: http://www.cjbarnes.co.uk
logo: /favicon-194x194.png
social:
    name: Chris Barnes
    links: ['https://twitter.com/cJbarnesUK','https://www.linkedin.com/in/cjbarnesuk']
author:
  twitter: cJbarnesUK
twitter:
  username: cJbarnesUK
facebook:
  app_id: 1560564457582577
  admins: 1086926316
google_site_verification:

# Number of articles to show in RSS feed
feed_limit: 20

# Permalinks.
permalink: /blog/:title-:year-:month-:day/
relative_permalinks: false

# Pagination.
paginate: 5
paginate_path: /blog/page:num

# Process _pages folder, and output the Sass and JS source for use in sourcemaps
# (and for non-GitHub users).
include: ['_pages','*.scss','_src']

# Don't process working copies of images, config files, or readmes.
exclude: ['*.psd','*.ai','*.eps','*.codekit','*.lock','Gemfile','README.md','gulpfile.js','package.json','node_modules']

# Don't process posts with future dates.
future: false

# Mark the end of the automatically-generated excerpt.
excerpt_separator: <!--more-->

# Markdown parser and code highlighter.
markdown: kramdown
kramdown:
  input: GFM # support GitHub-Flavored Markdown.
  parse_block_html: true

# Enabled plugins.
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed

# Frontmatter defaults for posts and pages.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "standard"
      author: chris barnes
  -
    scope:
      path: ""
      type: "posts"
    values:
      format: "thoughts"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      format: "thoughts"

# Sass compilation. Currently unused.
# sass:
#   style: :compressed
#   sass_dir: css/sass_dir
